libgst: Fix the cint.c build on XNU/Darwin
fdatasync appears to be available when linking but there is
no declaration in XNU. Move from checking the function to
checking the declaration.

Fixes:

cint.c:663:35: error: use of undeclared identifier 'fdatasync'
  _gst_define_cfunc ("fdatasync", fdatasync);
                                  ^

2015-05-21  Holger Hans Peter Freyther  <holger@freyther.de>

	* configure.ac: Move from AC_CHECK_FUNCS_ONCE to AC_CHECK_DECLS
	for fdatasync.

2015-05-21  Holger Hans Peter Freyther  <holger@freyther.de>

	* cint.c: Change to use #if instead of #ifdef and update
	the macro to change for.